### ISSUE TITLE
OpenGl Not Rendering

### ISSUE THREAD

**Issue by BrodenFrailingson** [TASUIT-Inc/CGT-Year-3-Labyrintian#1]
This issue is in relation to the Refactor branch.

The Issue: Even though everything looks fine, the staging is correct, shaders are "working" fine and it runs with out errors, nothing is being drawn to the screen, The error seems to be in the GBuffer class but after looking over it for a day I can't seem to find the error.

The expected output should be a model of a shotgun.

**Comment by pkeir** [comment]
When I run it I'm seeing a few runtime errors. One is clear (Shotgun.obj is missing), but there are a few other error messages which may be due to missing files:

```
ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
Vertex info
-----------
(0) : error C5145: must write to gl_Position

 -- --------------------------------------------------- -- 
ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
Vertex info
-----------
(0) : error C5145: must write to gl_Position

 -- --------------------------------------------------- -- 
ERROR::ASSIMP:: Unable to open file "src/CodeMeat_Core/Objects/Models/ModelPool/E1M1/Shotgun.obj".
Texture failed to load at path: Dev.png
```

**Comment by BrodenFrailingson** [comment]
Hi Paul.

Are you free to hop in a call via Microsoft teams or join the voice chat in group 1’s discord server as I believe most of the issues you see are related to GitHub, if not then I will send you a link to the file hosted on OneDrive as I don’t get these errors.

Yours Sincerely, Brodie

**Comment by pkeir** [comment]
I see your member variable names start with "m_". Beware naming local variables in the same way: e.g. `m_Cube` in `Engine::init`. You do though pass *it* to `REngine::Instance()->Submit` (so that can work) ... but local variable `m_SkyLight` is not used after the line of its declaration, and so you have no lights (`Renderer::m_Lights` is empty). Perhaps use `new`, and pass that `Light` pointer also also to `REngine::Instance()->Submit`?

This is still unlikely to be the issue. I would advise rolling back to a prior commit. Hopefully these should all build and run; otherwise you may have to revert to commit 557d659e3247fe0e5776e88a8e54f47909bfb15a and add the changes in again by hand, but this time in smaller steps.
